# Created with YamlCreate.ps1 v2.1.2 $debug=QUSU.7-2-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Amazon.Corretto.17
PackageVersion: 17.0.4.9
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- java
FileExtensions:
- jar
- java
Installers:
- Architecture: x64
  InstallerUrl: https://corretto.aws/downloads/resources/17.0.4.9.1/amazon-corretto-17.0.4.9.1-windows-x64.msi
  InstallerSha256: 1d64c109bd6fb0b0f941ce02adcfdea795d234d8a1b87c713d18062875153b2e
  ProductCode: '{2679DAFA-0D6A-4EFD-BDFF-BB20FBE9208A}'
ManifestType: installer
ManifestVersion: 1.1.0
